In [45]:
import numpy as np
import pandas as pd
from collections import OrderedDict
import requests

In [3]:
country_default = OrderedDict([('Canada', 'CAN'), ('United States', 'USA'), 
  ('Brazil', 'BRA'), ('France', 'FRA'), ('India', 'IND'), ('Italy', 'ITA'), 
  ('Germany', 'DEU'), ('United Kingdom', 'GBR'), ('China', 'CHN'), ('Japan', 'JPN')])
countries = country_default

In [4]:
countries

OrderedDict([('Canada', 'CAN'),
             ('United States', 'USA'),
             ('Brazil', 'BRA'),
             ('France', 'FRA'),
             ('India', 'IND'),
             ('Italy', 'ITA'),
             ('Germany', 'DEU'),
             ('United Kingdom', 'GBR'),
             ('China', 'CHN'),
             ('Japan', 'JPN')])

In [5]:
countries.values()

odict_values(['CAN', 'USA', 'BRA', 'FRA', 'IND', 'ITA', 'DEU', 'GBR', 'CHN', 'JPN'])

In [6]:
countries.keys()

odict_keys(['Canada', 'United States', 'Brazil', 'France', 'India', 'Italy', 'Germany', 'United Kingdom', 'China', 'Japan'])

In [9]:
country_filter = list(countries.values())
country_filter = [x.lower() for x in country_filter]
country_filter = ';'.join(country_filter)
country_filter

'can;usa;bra;fra;ind;ita;deu;gbr;chn;jpn'

In [43]:
indicators = ['AG.LND.ARBL.HA.PC']

data_frames = [] # stores the data frames with the indicator data of interest
urls = [] # url endpoints for the World Bank API

In [56]:
for indicator in indicators:
    url = 'http://api.worldbank.org/v2/countries/' + country_filter +\
    '/indicators/' + indicator + '?date=1990:2015&per_page=1000&format=json'
    urls.append(url)

    try:
        r = requests.get(url)
        data = r.json()[1]
        print(len(data))
    except:
        print('could not load data ', indicator)

#     for i, value in enumerate(data):
#         value['indicator'] = value['indicator']['value']
#         value['country'] = value['country']['value']

    data_frames.append(data)

  # first chart plots arable land from 1990 to 2015 in top 10 economies 
  # as a line chart

graph_one = []
df_one = pd.DataFrame(data_frames[0])

# filter and sort values for the visualization
# filtering plots the countries in decreasing order by their values
df_one = df_one[(df_one['date'] == '2015') | (df_one['date'] == '1990')]
df_one.sort_values('value', ascending=False, inplace=True)

# this  country list is re-used by all the charts to ensure legends have the same
# order and color
countrylist = df_one.country.unique().tolist()

260

In [63]:
df_one = pd.DataFrame(data_frames[0])
df_one = df_one[(df_one['date'] == '2015') | (df_one['date'] == '1990')]
df_one.sort_values('value', ascending=False, inplace=True)
df_one

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
51,Arable land (hectares per person),Canada,CAN,1990,1.643269,,,2
26,Arable land (hectares per person),Canada,CAN,2015,1.221368,,,2
259,Arable land (hectares per person),United States,USA,1990,0.743826,,,2
234,Arable land (hectares per person),United States,USA,2015,0.474878,,,2
0,Arable land (hectares per person),Brazil,BRA,2015,0.398652,,,2
25,Arable land (hectares per person),Brazil,BRA,1990,0.340134,,,2
129,Arable land (hectares per person),France,FRA,1990,0.305393,,,2
104,Arable land (hectares per person),France,FRA,2015,0.277674,,,2
181,Arable land (hectares per person),India,IND,1990,0.187179,,,2
207,Arable land (hectares per person),Italy,ITA,1990,0.158888,,,2
103,Arable land (hectares per person),Germany,DEU,1990,0.150706,,,2
78,Arable land (hectares per person),Germany,DEU,2015,0.145054,,,2
156,Arable land (hectares per person),India,IND,2015,0.119424,,,2
155,Arable land (hectares per person),United Kingdom,GBR,1990,0.115638,,,2
77,Arable land (hectares per person),China,CHN,1990,0.109057,,,2
182,Arable land (hectares per person),Italy,ITA,2015,0.108693,,,2
130,Arable land (hectares per person),United Kingdom,GBR,2015,0.092312,,,2
52,Arable land (hectares per person),China,CHN,2015,0.086784,,,2
233,Arable land (hectares per person),Japan,JPN,1990,0.038596,,,2
208,Arable land (hectares per person),Japan,JPN,2015,0.033074,,,2